name: bit_flag
description: An object uses the Integer Flag and its methods to calculator it.
version: 1.0.0
repository: https://github.com/sonnts996/bit_flag

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.9
